# Generated by Django 5.1.6 on 2025-03-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planconfirmation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
