# Generated by Django 4.0 on 2025-03-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
    ]
