# Generated by Django 4.0 on 2025-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planconfirmation',
            name='elatitude',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='elongitude',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='rlatitude',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='rlongitude',
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='event_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='event_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='restaurant_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='restaurant_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
