# Generated by Django 4.0 on 2025-03-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_planconfirmation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='planconfirmation',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
