# Generated by Django 4.0 on 2025-02-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Biography',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Favorite_Food',
            new_name='favorite_food',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Picture',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Fname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Lname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
