# Generated by Django 4.0 on 2025-03-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_auto_20250312_2032'),
        ('myproject', '0002_remove_planconfirmation_elatitude_and_more'),
    ]

    operations = [
    ]
