# Generated by Django 4.0 on 2025-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_planconfirmation_formatted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='planconfirmation',
            name='event_image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='restaurant_image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
