# Generated by Django 4.0 on 2025-03-19 19:05
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_planconfirmation_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planconfirmation',
            name='ai_processing_time_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
