# Generated by Django 4.0 on 2025-03-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_planconfirmation_ai_processing_time_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planconfirmation',
            name='ai_processing_time_seconds',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='created_at',
        ),
    ]
