# Generated by Django 4.0 on 2025-03-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_remove_customuser_favorite_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
                ('occasion', models.CharField(max_length=255)),
                ('order', models.TextField()),
                ('restaurant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_website', models.URLField(blank=True, null=True)),
                ('restaurant_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('restaurant_reservation_time', models.CharField(blank=True, max_length=50, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_address', models.CharField(blank=True, max_length=255, null=True)),
                ('event_website', models.URLField(blank=True, null=True)),
                ('event_start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('event_end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.customuser')),
            ],
        ),
    ]
