# Generated by Django 4.0 on 2025-03-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_planconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planconfirmation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='event_website',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='restaurant_rating',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='restaurant_reservation_time',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='restaurant_website',
        ),
        migrations.AlterField(
            model_name='planconfirmation',
            name='guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planconfirmation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
