# Generated by Django 4.0 on 2025-03-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_remove_planconfirmation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planconfirmation',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='planconfirmation',
            name='location',
        ),
        migrations.AlterField(
            model_name='planconfirmation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planconfirmation',
            name='occasion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
