# Generated by Django 4.0 on 2025-03-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_remove_planconfirmation_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planconfirmation',
            name='elatitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='elongitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='rlatitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='planconfirmation',
            name='rlongitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
